apiVersion: v1
kind: Lockfile
metadata:
  name: fedora-base-lockfile
  generated_from: local-repo.lockfile.in
packages:
- name: audit
  version: 4.1.1-2.fc44
  arch: x86_64
  rpm_path: oci://quay.io/bcook/rpms:audit-4.1.1-2.fc44
  checksum: sha256:52b67b31547b649ff63202cbd3545405ad288d1f789c908acfb0a0ec4f12ed14
  size: 213015
  oci_ref: oci://quay.io/bcook/rpms:audit-4.1.1-2.fc44
  original_rpm_path: file:///workspace/prefetch/repo/audit-4.1.1-2.fc44.x86_64.rpm
- name: bash
  version: 5.3.0-2.fc43
  arch: x86_64
  rpm_path: oci://quay.io/bcook/rpms:bash-5.3.0-2.fc43
  checksum: sha256:cc112d6284d1be418582f30eea2c18545c0ac5f6fe820219d04c6e8fe2cfff7f
  size: 1960689
  oci_ref: oci://quay.io/bcook/rpms:bash-5.3.0-2.fc43
  original_rpm_path: file:///workspace/prefetch/repo/bash-5.3.0-2.fc43.x86_64.rpm
- name: bash
  version: 5.3.0-2.fc43
  arch: aarch64
  rpm_path: oci://quay.io/bcook/rpms:bash-5.3.0-2.fc43
  checksum: sha256:621982221694140270abd51ccc15e576c77c5c1415bab97abf66ebb3ca00aa93
  size: 1928615
  oci_ref: oci://quay.io/bcook/rpms:bash-5.3.0-2.fc43
  original_rpm_path: file:///workspace/prefetch/repo/bash-5.3.0-2.fc43.aarch64.rpm
- name: bzip2
  version: 1.0.8-21.fc43
  arch: x86_64
  rpm_path: oci://quay.io/bcook/rpms:bzip2-1.0.8-21.fc43
  checksum: sha256:f208d9c390a8f404dbf2d6e7fda37c20214785a10a01cb7e46989327f6730390
  size: 52838
  oci_ref: oci://quay.io/bcook/rpms:bzip2-1.0.8-21.fc43
  original_rpm_path: file:///workspace/prefetch/repo/bzip2-1.0.8-21.fc43.x86_64.rpm
- name: coreutils
  version: 9.7-5.fc43
  arch: x86_64
  rpm_path: oci://quay.io/bcook/rpms:coreutils-9.7-5.fc43
  checksum: sha256:cd9eac22543712272a4aa531e5369de77b97837a3661f7faa3c59e068de10915
  size: 1144576
  oci_ref: oci://quay.io/bcook/rpms:coreutils-9.7-5.fc43
  original_rpm_path: file:///workspace/prefetch/repo/coreutils-9.7-5.fc43.x86_64.rpm
- name: cpio
  version: 2.15-6.fc43
  arch: x86_64
  rpm_path: oci://quay.io/bcook/rpms:cpio-2.15-6.fc43
  checksum: sha256:b912f1ee96b2b087ef4ff88b15fe626b82c0a1b71a2f5fdca21d3c40441466e5
  size: 300032
  oci_ref: oci://quay.io/bcook/rpms:cpio-2.15-6.fc43
  original_rpm_path: file:///workspace/prefetch/repo/cpio-2.15-6.fc43.x86_64.rpm
- name: crypto-policies
  version: 20250714-4.gitcd6043a.fc44
  arch: noarch
  rpm_path: oci://quay.io/bcook/rpms:crypto-policies-20250714-4.gitcd6043a.fc44
  checksum: sha256:b7b8a599585dc6c523afaaf45416c916ef7c3ee1f7e07ae8caceaf9913641c95
  size: 100826
  oci_ref: oci://quay.io/bcook/rpms:crypto-policies-20250714-4.gitcd6043a.fc44
  original_rpm_path: file:///workspace/prefetch/repo/crypto-policies-20250714-4.gitcd6043a.fc44.noarch.rpm
- name: diffutils
  version: 3.12-3.fc43
  arch: x86_64
  rpm_path: oci://quay.io/bcook/rpms:diffutils-3.12-3.fc43
  checksum: sha256:149f32c1d803d1053e08da393a439e008cd4cdf714b69f12c5de90ba4ec555ec
  size: 401408
  oci_ref: oci://quay.io/bcook/rpms:diffutils-3.12-3.fc43
  original_rpm_path: file:///workspace/prefetch/repo/diffutils-3.12-3.fc43.x86_64.rpm
- name: filesystem
  version: 3.18-50.fc43
  arch: x86_64
  rpm_path: oci://quay.io/bcook/rpms:filesystem-3.18-50.fc43
  checksum: sha256:2c8bbed1758f2884d62978d0f96e27f37cdcfc910593beaad5135808ce49ea13
  size: 1394688
  oci_ref: oci://quay.io/bcook/rpms:filesystem-3.18-50.fc43
  original_rpm_path: file:///workspace/prefetch/repo/filesystem-3.18-50.fc43.x86_64.rpm
- name: findutils
  version: 4.10.0-6.fc43
  arch: x86_64
  rpm_path: oci://quay.io/bcook/rpms:findutils-4.10.0-6.fc43
  checksum: sha256:db683fa3e84ab72bebb9be3fa43d3ee0aad49a303395bc839f8b9dd7829ba6fe
  size: 563200
  oci_ref: oci://quay.io/bcook/rpms:findutils-4.10.0-6.fc43
  original_rpm_path: file:///workspace/prefetch/repo/findutils-4.10.0-6.fc43.x86_64.rpm
- name: gawk
  version: 5.3.2-2.fc43
  arch: x86_64
  rpm_path: oci://quay.io/bcook/rpms:gawk-5.3.2-2.fc43
  checksum: sha256:0ec4e62741c463d98148dd04f513ce99b4265914e930bdf2557ee5a5cd1369d4
  size: 1146880
  oci_ref: oci://quay.io/bcook/rpms:gawk-5.3.2-2.fc43
  original_rpm_path: file:///workspace/prefetch/repo/gawk-5.3.2-2.fc43.x86_64.rpm
- name: glibc
  version: 2.42.9000-1.fc44
  arch: x86_64
  rpm_path: oci://quay.io/bcook/rpms:glibc-2.42.9000-1.fc44
  checksum: sha256:712b911175d4ef4cb4af8904878f4dcfa60eab4b25d20e213bc35e8dd7d561a7
  size: 2326528
  oci_ref: oci://quay.io/bcook/rpms:glibc-2.42.9000-1.fc44
  original_rpm_path: file:///workspace/prefetch/repo/glibc-2.42.9000-1.fc44.x86_64.rpm
- name: grep
  version: 3.12-2.fc43
  arch: x86_64
  rpm_path: oci://quay.io/bcook/rpms:grep-3.12-2.fc43
  checksum: sha256:d9549130679b3868cc4a33c6df5b2d1516d8776761af435e8c55ebacb7e53424
  size: 306176
  oci_ref: oci://quay.io/bcook/rpms:grep-3.12-2.fc43
  original_rpm_path: file:///workspace/prefetch/repo/grep-3.12-2.fc43.x86_64.rpm
- name: setup
  version: 2.15.0-26.fc43
  arch: noarch
  rpm_path: oci://quay.io/bcook/rpms:setup-2.15.0-26.fc43
  checksum: sha256:bc8674d724c5000b0381c87b77430d2858f7caffac223161b7a2852ace87bed3
  size: 160768
  oci_ref: oci://quay.io/bcook/rpms:setup-2.15.0-26.fc43
  original_rpm_path: file:///workspace/prefetch/repo/setup-2.15.0-26.fc43.noarch.rpm
- name: util-linux
  version: 2.41.1-16.fc44
  arch: x86_64
  rpm_path: oci://quay.io/bcook/rpms:util-linux-2.41.1-16.fc44
  checksum: sha256:a5c62620edb5b276580810663dd3cc458ed796bc23b755c1ef28ffbd634e2d28
  size: 1247232
  oci_ref: oci://quay.io/bcook/rpms:util-linux-2.41.1-16.fc44
  original_rpm_path: file:///workspace/prefetch/repo/util-linux-2.41.1-16.fc44.x86_64.rpm
